FROM ruby


# rails s -b 0.0.0.0 -p 3000
# "rails", "s", "-b" "0.0.0.0" "-p" "3000"

# build ft-rails
# docker build -t ft-rails:on-build ./ft_rails

# build it
# docker build --tag ex02 ./

# run it
# docker run --interactive --tty --rm ex02
